### ISSUE TITLE
HTTPS issue widgets.sourcecred.io

### ISSUE THREAD

**Issue by Beanow** [sourcecred/widgets#20]
The TLS certificate does not match the subdomain here:
https://widgets.sourcecred.io/sourcecred-widgets-contributors.svg

Here they suggest you re-add the CNAME to get a let's encrypt cert.
https://help.github.com/en/articles/troubleshooting-custom-domains#https-errors

**Comment by Beanow** [comment]
I've tested the above suggestion, but no luck. Perhaps you can try the HTTPS toggle in the repo settings @decentralion ?

**Comment by teamdandelion** [comment]
I checked the "enforce https" box in the settings and it seems to be working now.

@Beanow please confirm. :)

**Comment by Beanow** [comment]
:+1: It's fixed, the certificate is now for widgets.sourcecred.io
